feat: update styling
iprado78/fullstack-iex-stock-ticker pull request #29
Opened 2021-04-13 20:28 UTC by gracescharf

## Description

* grabs the styling and layout changes from garbage-fire branch
* i'm noticing that the company overview isn't receiving the data when summary stats are -- even though they're both listening for tickerSelections$ which has the 'shareReplay(1)' on it  
## Related Issues

- Closes ISSUE

## Testing

1. Step 1

2021-04-13 21:19 UTC, iprado78 requested changes

2021-04-13 21:19 UTC, iprado78 commented on components/CompanyOverview/CompanyOverview.module.scss
> +@import "../../styles/variables.scss";
Use '@/styles/...'

2021-04-13 21:19 UTC, iprado78 commented on components/CompanyOverview/CompanyOverview.module.scss
> +    h3 {
Duplicate h3 declaration.  Consolidate.  Also, I think semantically these should be h2

2021-04-13 21:19 UTC, iprado78 commented on components/CompanyOverview/CompanyOverview.tsx
> +          <img
We should start using that Next image component.

2021-04-13 21:19 UTC, iprado78 commented on components/Footer.tsx
> +import styles from "@/styles/Home.module.scss"
May be overkill, but I think we should move the styles out of Home and into a Footer.module.scss. Ditto for the other Home components.

2021-04-13 21:19 UTC, iprado78 commented on components/Header/Header.tsx
> +        <img src="USBankLogo.jpeg" alt="US Bank Logo" width="200" />
See other comment re: Image component

2021-04-13 21:19 UTC, iprado78 commented on components/Main.tsx
> -import styles from "@/styles/Home.module.css"
See above.  Header.module.scss

2021-04-13 21:19 UTC, iprado78 commented on components/StatsTable/StatsTable.module.scss
> +@import "../../styles/variables.scss";
"@/styles/.."

2021-04-13 21:19 UTC, iprado78 commented on components/SummaryStats/SummaryStats.tsx
> -  if (!Object.keys(summaryStats).length) {
Good catch that this is no longer necessary

2021-04-13 21:19 UTC, iprado78 commented on components/Tabs/Tabs.tsx
> +        <img src="https://media.giphy.com/media/BEob5qwFkSJ7G/giphy.gif" />
Nice.  Image component.  Also, remember alt attribute!

2021-04-15 18:12 UTC, gracescharf commented on components/Main.tsx
> -import styles from "@/styles/Home.module.css"
noted -- might make this a todo tho?

2021-04-15 18:57 UTC, iprado78 approved these changes, later dismissed

2021-04-15 18:57 UTC, iprado78 commented on styles/variables.scss
> +$tablet: 768px;
💯

2021-04-15 18:57 UTC, iprado78 commented on components/Footer.tsx
>    return (
Also, this Footer is pretty broken on the mobile view.  Maybe we just kill it until we have time to make a true sticky but responsive footer.

2021-04-15 18:57 UTC, iprado78 commented on components/Tabs/Tabs.tsx
> +            alt="Spongebob looking very sad with teary eyes and a quivering mouth."
🦖

2021-04-15 18:57 UTC, iprado78 commented on styles/z-order.scss
> +/*
🥳

2021-04-15 19:14 UTC, iprado78 approved these changes

2021-04-15 19:15 UTC, merged